spring.application.name=workflow-worker
spring.datasource.url=jdbc:postgresql://postgres:5432/workflow_dev
spring.datasource.username=wf_user
spring.datasource.password=wf_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.access=unrestricted
management.endpoint.info.access=unrestricted


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.endpoints.web.base-path=/actuator
management.server.port=8080